services:
  fda-crawler:
    build: .
    container_name: fda-guidance-harvester-simple
    environment:
      # Database Configuration (REQUIRED)
      DATABASE_URL: postgresql+asyncpg://sanatanupmanyu:ksDq2jazKmxxzv.VxXbkwR6Uxz@host.docker.internal:5432/quriousri_db
      
      # Optional Configuration (with defaults)
      SCHEMA_NAME: source
      MAX_CONCURRENCY: 4
      RATE_LIMIT: 1.0
      
      # HTTP Configuration
      CONNECT_TIMEOUT: 30
      READ_TIMEOUT: 60
      MAX_RETRIES: 3
      RETRY_DELAY: 1.0
      
      # User Agent
      USER_AGENT: "FDA-Crawler/1.0"
    
    # Uncomment to run specific commands
    # command: ["fda-crawler", "test", "--limit", "10"]
    # command: ["fda-crawler", "resume", "session-id-here"]
    
    restart: unless-stopped
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
